FROM golang:1.12-alpine

WORKDIR /app

# ENV GO111MODULE=on
# WORKDIR /go/src/github.com/unmock/example-golang/

COPY . .

RUN set -ex; \
    apk update; \
    apk add --no-cache git

RUN go mod download

CMD CGO_ENABLED=0 go test ./...
