FROM golang:1.12-alpine

WORKDIR /app

# ENV GO111MODULE=on
# WORKDIR /go/src/github.com/unmock/example-golang/

COPY . .

RUN set -ex; \
    apk update; \
    apk add --no-cache git


RUN go mod download

# Trust Unmock certificate
RUN wget https://raw.githubusercontent.com/unmock/unmock-js/dev/packages/unmock-server/certs/ca.pem
ENV SSL_CERT_FILE ca.pem

CMD CGO_ENABLED=0 go test ./...
