FROM golang:1.12-alpine

WORKDIR /app

# ENV GO111MODULE=on
# WORKDIR /go/src/github.com/unmock/example-golang/

COPY . .

RUN set -ex; \
    apk update; \
    apk add --no-cache git

RUN go mod download

ENV GITHUB_TOKEN fake-token
ENV https_proxy http://unmock-server:8008
ENV NO_PROXY gopkg.in
ENV SSL_CERT_FILE certs/cert.pem

CMD CGO_ENABLED=0 go test ./...
