version: 2.1
orbs:
  unmock: unmock/unmock@dev:0.0.14

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - restore_cache: # restores saved cache if no changes are detected since last run
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          keys:
            - v1-pkg-cache
      - run: go build
      - save_cache: # Store cache in the /go/pkg directory
          key: v1-pkg-cache
          paths:
            - "/go/pkg"
      - setup_remote_docker
      - run:
          name: "Run tests"
          command: docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit
      - run:
          name: "Stop containers"
          command: docker-compose down

workflows:
  version: 2
  test-and-build:
    jobs:
      - build
