version: 2.1
orbs:
  unmock: unmock/unmock@dev:0.0.14

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - restore_cache: # restores saved cache if no changes are detected since last run
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          keys:
            - v1-pkg-cache
      - run: go build
      - save_cache: # Store cache in the /go/pkg directory
          key: v1-pkg-cache
          paths:
            - "/go/pkg"
      - unmock/start:
          domains: "api.github.com"
      - unmock/set:
          code: 200
      - run:
          command: go test
          environment:
            GITHUB_TOKEN: fake-token
            NO_PROXY: gopkg.in
      - unmock/stop

  build-with-docker:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Prepare certificate in certs/ folder"
          command: docker run -v `pwd`/certs:/app/certs unmock/unmock-server bash build-cert.sh api.github.com certs/
      - run:
          name: "Run tests"
          command: docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit
      - run:
          name: "Stop containers"
          command: docker-compose down

workflows:
  version: 2
  test-and-build:
    jobs:
      - build
      - build-with-docker
